version: 0.2

phases:
  install:
    commands:
       - home=`pwd` 
       - apt update
       - apt-get install -y git gcc libffi-dev libssl-dev make zip build-essential zlib1g-dev openssl libpq-dev 
       - add-apt-repository ppa:jonathonf/python-3.6
       - apt-get update
       - apt-get install -y python3.6 python3-pip python3-dev
       - python3.6 -m venv venv --without-pip
       - ln -sf /usr/bin/pip3 $home/venv/bin/pip
       - . venv/bin/activate 
       - pip install --upgrade pip setuptools tld --ignore-installed six
       - (. venv/bin/activate && make develop)
       - venv/bin/pip install -e .
       - venv/bin/pip install awscli
       - cp -r venv/lib/python3.6/site-packages/. aws_lambda_libs
       - cp -r venv/lib64/python3.6/site-packages/. aws_lambda_libs
       - python3 bless_python/bless_deploy.py
