#!/bin/bash

KEYPAIR=blesskeypair$1

# Create aws key pair
KEY_PAIR_NAME=$(aws ec2 create-key-pair --key-name $KEYPAIR --query 'KeyMaterial' --output text > $KEYPAIR.pem)

echo 'Created key pair'

# Set permissions for the keypair 
chmod 600 $KEYPAIR.pem

echo 'Gave key pair new permissions'

# Find default subnet for ec2 creation 
DEFAULT_SUBNET=$(aws ec2 describe-subnets --filters Name=defaultForAz,Values=true --query 'Subnets[0].SubnetId' --output text)

echo $DEFAULT_SUBNET


# Create ec2 instance
INSTANCE_ID=$(aws ec2 run-instances --image-id ami-009d6802948d06e52 --count 1 --instance-type t2.micro --key-name $KEYPAIR --subnet-id $DEFAULT_SUBNET --query 'Instances[*].InstanceId' --output text --user-data-file user_data.sh)

echo $INSTANCE_ID


# Wait until instance is complete
aws ec2 wait instance-running --instance-ids $INSTANCE_ID	 


# Querying for public IP address for log in
INSTANCE_IP=$(aws ec2 describe-instances  --instance-ids $INSTANCE_ID --query Reservations[*].Instances[*].PublicIpAddress --output text)

echo $INSTANCE_IP

# Move key into ssh file
mv $KEYPAIR.pem ~/.ssh


# Log on to the ec2 instance
ssh -i ~/.ssh/$KEYPAIR.pem ec2-user@$INSTANCE_IP


# 
