#!/bin/bash

if [ $# -eq 0 ]; then
echo "Missing argument number"
exit
fi

POLICYNAME=bkp$1
ROLENAME=bkr$1
ALIASNAME=bkk$1
PASSWORD='abc123'
KEY_ID=f8882b60-86e7-4799-aa59-412c1044a762
KEY_ARN=arn:aws:kms:us-east-1:497773990203:key/f8882b60-86e7-4799-aa59-412c1044a762

# Create kms key and query for key id

#KEY_ID=$(aws kms create-key --query KeyMetadata.KeyId --output text )
echo $KEY_ID

# Query for the kms key id
#KEY_ARN=$(aws kms describe-key --key-id $KEY_ID  --query KeyMetadata.Arn --output text)
echo $KEY_ARN

# Create alias for key

# aws kms create-alias --alias-name alias/$ALIASNAME --target-key-id $KEY_ARN


# JSON code for kms policy
BLESSPOLICY='{ "Version": "2012-10-17",
          "Statement": [ {
              "Action": [
                  "kms:GenerateRandom", "logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"
              ],
              "Effect": "Allow",
              "Resource": "*"
          },
          { "Sid": "AllowKMSDecryption",
            "Effect": "Allow",
            "Action": [
               "kms:Decrypt", "kms:DescribeKey"
            ],
            "Resource": [
                 "'$KEY_ARN'"
            ] } ] }'

echo $BLESSPOLICY

# Create the actual policy
POLICY_ARN=$(aws iam create-policy --policy-name $POLICYNAME --policy-document "$BLESSPOLICY" --query Policy.Arn --output text)
echo $POLICY_ARN

# JSON code for kms role
BLESSROLE='{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}'

echo $BLESSROLE


# Create trust role for lambda
ROLE_ARN=$(aws iam create-role --role-name $ROLENAME --assume-role-policy-document "$BLESSROLE" --query Role.Arn --output text)

echo $ROLE_ARN

# Attach policy to role
aws iam attach-role-policy --role-name $ROLENAME  --policy-arn "$POLICY_ARN"

# Make a directory for the Lambda config files
mkdir lambda_configs

# Create a SSH CA key in lambda_configs
ssh-keygen -t rsa -N "$PASSWORD" -b 4096 -f ./lambda_configs/bless-cauthority2- -C "SSH CA Key"


# Encrypt kms key
B64_PASS=$(aws kms encrypt --key-id $KEY_ID --plaintext $PASSWORD --query CiphertextBlob --output text | base64)


# Create bless_deploy.cfg
. ./bless_deploy_config


# Compile Lambda libaries into a zip file 
make publish 

de=$(pwd)
echo $de


# Create Lambda
. ./create_lambda $1

# Create Key Pair
. ./keypair_ec2 $1 
