AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer': {}
Resources:
  blessiamrole3:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: blesscodebuildrole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: blesscodebuildpolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 'iam:GetRole'
                  - 'iam:CreateRole'
                  - 'iam:AttachRolePolicy'
                  - 'logs:PutLogEvents'
                  - 'iam:CreatePolicy'
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 'iam:PassRole'
                  - 'logs:CreateLogStream'
                  - 'kms:Encrypt'
                  - 'iam:ListAttachedRolePolicies'
                  - 'kms:CreateAlias'
                  - 'kms:DescribeKey'
                  - 's3:GetObjectVersion'
                Effect: Allow
                Resource: '*'
              - Sid: VisualEditor1
                Effect: Allow
                Action:
                  - 'lambda:CreateFunction'
                  - 'kms:CreateKey'
                Resource: '*'
              - Sid: VisualEditor2
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                Resource:
                  - arn:aws:logs:us-east-1:497773990203:log-group:/aws/codebuild/bless-deploy
                  - arn:aws:logs:us-east-1:497773990203:log-group:/aws/codebuild/bless-deploy:*
